roles = [
    "A knight who just lost his horse",
    "A boy who just lost his favourite toy",
    "A girl who lost her balloon to the sky and can't get it back.",
    "A boy whose ice cream fell off the cone before he could take a bite.",
    "A child who built the tallest block tower, only to have it knocked down by a pet.",
    "A young wizard whose magic trick didn't go as planned in front of friends.",
    "A pirate who can't find where they buried their treasure in the sandbox.",
    "A superhero who couldn't fly as high as they wanted to during playtime.",
    "A mermaid who lost her special shell necklace during a swim.",
    "A young knight who can't find their pretend dragon to save the kingdom.",
    "A princess whose fairy garden didn't grow as she expected.",
    "A young detective who can't solve the mystery of the missing cookie.",
    "A space explorer who's pretend rocket won't take off.",
    "An artist who spilled paint on their favorite drawing.",
    "A singer who forgot the words to their song during a performance for their family.",
    "A young chef whose mud pie didn't turn out as delicious as planned.",
    "A child who lost their first tooth but can't find it for the Tooth Fairy.",
    "A little racer whose toy car won't go as fast as their friend's.",
    "A young gardener whose plant won't sprout, no matter how much they water it.",
    "A storybook character who can't remember the way back to their magical land."
]